ci: add symlink ci

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,4 +1,4 @@
-name: CI
+name: Main CI
 
 on:
   pull_request:
@@ -8,6 +8,7 @@ on:
 jobs:
   ci:
     runs-on: ubuntu-latest
+    timeout-minutes: 10
     steps:
       - uses: actions/checkout@v4
       - name: Setup ansible
@@ -16,3 +17,15 @@ jobs:
         run: cd ansible && ansible-galaxy install -r requirements.yml
       - name: Run ansible-lint
         run: cd ansible && ansible-lint
+  check_symlinks:
+    runs-on: ubuntu-latest
+    timeout-minutes: 10
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v3
+      - name: Find symlinks
+        run: |
+          if [ -n "$(find . -type l)" ]; then
+            echo "Error: Found symbolic links in the repository"
+            exit 1
+          fi
