ci: add symlink ci (#4)
* ci: add symlink ci

* ci: show symlinks

* ci: fix

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,4 +1,4 @@
-name: CI
+name: Main CI
 
 on:
   pull_request:
@@ -6,8 +6,9 @@ on:
       - "main"
 
 jobs:
-  ci:
+  lint:
     runs-on: ubuntu-latest
+    timeout-minutes: 10
     steps:
       - uses: actions/checkout@v4
       - name: Setup ansible
@@ -16,3 +17,16 @@ jobs:
         run: cd ansible && ansible-galaxy install -r requirements.yml
       - name: Run ansible-lint
         run: cd ansible && ansible-lint
+  check_symlinks:
+    runs-on: ubuntu-latest
+    timeout-minutes: 10
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v3
+      - name: Find symlinks
+        run: |
+          if [ -n "$(find . -type l)" ]; then
+            echo "Error: Found symbolic links in the repository"
+            find . -type l
+            exit 1
+          fi
